=== msantrax/VehicleDynamics/Sandbox/Vega4/Jurid/Canais.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT monitor       (linha|spacer)*>
<!ELEMENT linha         (display)*>
<!ELEMENT display       (#PCDATA)>
<!ELEMENT spacer        (#PCDATA)>

<!ATTLIST monitor
          nome          CDATA "Monitor VD"
          desc          CDATA "Descrição da tela de monitor"
          bkg           CDATA "009500"
          maxlin        CDATA "8"
          maxcol        CDATA "8"
          porta         CDATA "/dev/ttyUSB0"
          baudrate      (4800|9600|19200|38400|57600|115200) "19200"
          databits      (7|8) "8"
          stopbits      (1|2) "1"
          paridade      (par|impar|none) "none"
          fluxo         (rts_cts|xon_xoff|none) "none"
          pool          CDATA "250"
>

<!ATTLIST spacer
          altura       CDATA #REQUIRED  
          borda        (nao|simples|bevel|inset) "nao"
          elastico     (sim|nao) "nao"
>

<!ATTLIST linha
          nome          CDATA "Linha de analise"
          desc          CDATA "Tipo de linha de analise"
          bkg           CDATA "009500"
          frg           CDATA "FFFFFF"
          visivel       (sim|nao) "nao"
          display       (default|escuro|realce|branco) "default"
          hd_tam        CDATA "14"
          hd_tipo       CDATA "Dialog"
          hd_estilo     (plano|negrito|italico) "plano"
          pn_tam        CDATA "20"
          pn_tipo       CDATA "Dialog"
          pn_estilo     (plano|negrito|italico) "negrito"        
>

<!ATTLIST display
          nome          CDATA #REQUIRED
          canal         CDATA #REQUIRED          
          desc          CDATA "Widget de display de dados"
          
          a0            CDATA "0"
          a1            CDATA "1"
          a2            CDATA "0"
          a3            CDATA "0"
          a4            CDATA "0"
          a5            CDATA "0"
          widget        (analogico|digital|timer|contador|velocidade) "analogico"
          mascara       CDATA "##0.0"
          maximo        CDATA "-1E06"
          minimo        CDATA "1E06"
          ring          CDATA "32"
          roffset       CDATA "0"
          rslope        CDATA "1"
          script        CDATA ""
          tipo          (SN|SO|CN|CO) "SN"
          unidade       CDATA "C"
          armazenar     (sim|nao) "nao"
          span          CDATA "1"


>

=== msantrax/VehicleDynamics/Sandbox/Vega4/Jurid/Canais_Green.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE monitor SYSTEM "Canais.dtd">


<monitor 
    nome="MONITOR DE TESTE" 
    desc="Monitor de teste (carga via arquivo XML)"
    bkg="009500">
    
    <spacer
        altura = "20">    
    </spacer>
    
    <linha
        visivel="nao"
        nome="Pressôes e Forças"
        pn_tam="30"
        hd_tam="10"
        hd_estilo="negrito">  
        <display
            nome="Pressão Dianteira"
            canal="9"
            desc="Pressão no cicuito dianteiro"
            mascara="##.##"
            unidade="PSI"
            span="2">
        </display>
        <display
            nome="Pressão Trazeira"
            canal="10"
            desc="Pressão no cicuito Trazeiro"
            mascara="##.##"
            unidade="PSI"
            span="2">
        </display>
        <display
            nome="Força no Pedal"
            mascara="##.##"
            unidade=""
            canal="13"
            span="2">
        </display>
        <display
            nome="Curso do Pedal"
            mascara="###"
            unidade="mm"
            a0="8.95E-01"
            canal="12"
            span="2">
        </display>
    </linha>
    
    <spacer
        altura = "20">    
    </spacer>
    
    <linha
        visivel = "nao"
        nome="Leituras de Temperatura "
        hd_tam="14"
        pn_tam="16">
        <display
            nome="Disco Esquerdo"
            canal="1"
            unidade="C"
            desc="Leitura do disco lado esquerdo">
        </display>
        <display
            nome="Disco Direito"
            canal="2">
        </display>
        <display
            nome="Pastilha Esquerda"
            canal="3">
        </display>
        <display
            nome="Pastilha Direita"
            canal="4">
        </display>
        <display
            nome="Temp. Ambiente"
            canal="14">
        </display>
        <display
            nome="LD spare2"
            canal="4">
        </display>
         <display
            nome="teste2"
            canal="14">
        </display>
        <display
            nome="teste3"
            canal="4">
        </display>
    </linha>
    
     <linha
        visivel = "nao">
        <display
            nome="Disco Esquerdo"
            digital= "sim"
            canal="1">
        </display>
        <display
            nome="Disco Direito"
            digital= "sim"
            canal="2">
        </display>
        <display
            nome="Pastilha Esquerda"
            digital = "sim"
            canal="3">
        </display>
        
    </linha>
    
    
</monitor>

=== msantrax/VehicleDynamics/TestRack_Config/Canais_XP.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE monitor SYSTEM "Canais.dtd">


<monitor 
    nome="MONITOR DE TESTE- Vehicle" 
    desc="Monitor de teste (carga via arquivo XML)"
    bkg="000000"
    porta="/dev/ttyS0"
    baudrate="19200"
    pool="100"
    >
   
    <linha
        pn_tam="14"
        hd_tam="10"
        hd_estilo="negrito">  
        <display
            nome="Termopar1"
            canal="1"
            mascara="#####"
            unidade="Cnt"
            span="1">
        </display>
        <display
            nome="Termopar2"
            canal="2"
            mascara="#####"
            unidade="Cnt"
            span="1">
        </display>
        <display
            nome="Termopar3"
            canal="3"
            mascara="#####"
            unidade="Cnt"
            span="1">
        </display>
        <display
            nome="04"
            canal="4"
            mascara="#####"
            unidade="Cnt"
            span="1">
        </display>
        <display
            nome="05"
            canal="5"
            mascara="#####"
            unidade="Cnt"
            span="1">
        </display>
        <display
            nome="06"
            canal="6"
            mascara="#####"
            unidade="Cnt"
            span="1">
        </display>
        <display
            nome="07"
            canal="7"
            mascara="#####"
            unidade="Cnt"
            span="1">
        </display>
        <display
            nome="08"
            canal="8"
            mascara="#####"
            unidade="Cnt"
            span="1">
        </display>
    </linha>
   
    <linha
        pn_tam="14"
        hd_tam="10"
        hd_estilo="negrito">  
        <display
            nome="09-Pressão-D"
            canal="9"
            mascara="#####"
            unidade="Cnt"
            span="1">
        </display>
        <display
            nome="09-Pressão-D"
            canal="10"
            mascara="#####"
            unidade="Cnt"
            span="1">
        </display>
        <display
            nome="11-Aceleração"
            canal="11"
            mascara="#####"
            unidade="Cnt"
            span="1">
        </display>
        <display
            nome="12-Curso Pedal"
            canal="12"
            mascara="#####"
            unidade="Cnt"
            span="1">
        </display>
        <display
            nome="13-Força Pedal"
            canal="13"
            mascara="#####"
            unidade="Cnt"
            span="1">
        </display>
        <display
            nome="14-Temp Ambiente"
            canal="14"
            mascara="#####"
            unidade="Cnt"
            span="1">
        </display>
        <display
            nome="15-Jurid Esq."
            canal="15"
            mascara="#####"
            unidade="Cnt"
            span="1">
        </display>
        <display
            nome="16-Jurid Dir."
            canal="16"
            mascara="#####"
            unidade="Cnt"
            span="1">
        </display>      
    </linha>
    
     <linha
        pn_tam="14"
        hd_tam="10"
        hd_estilo="negrito">  
        <display
            nome="Distancia"
            canal="17"
            mascara="########"
            unidade="Cnt"
            span="1">
        </display>
        
       
        
        <display
            nome="Timer"
            canal="22"
            widget="timer"
            span="1">
        </display>
        
         <display
            nome="Counter1"
            canal="22"
            widget="contador"
            span="1">
        </display>
            
    </linha>
    
     <linha
         visivel="sim"
         nome="Canais digitais"
         pn_tam="14"
         hd_tam="12"
         hd_estilo="negrito">  
    
          <display
            nome="20-Mark"
            canal="20"
            widget="digital"
            span="1">
        </display>
        <display
            nome="21-Separation"
            canal="21"
            widget="digital"
            span="1">
        </display>
        <display
            nome="22-Trigger"
            canal="22"
            widget="digital"
            span="1">
        </display>
        
     </linha>
     
</monitor>
